definitions:
  domain.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  domain.LoginResponse:
    properties:
      expireTime:
        type: string
      isValid:
        type: boolean
      token:
        type: string
      userId:
        type: integer
    type: object
  domain.TaskAddReq:
    properties:
      createUserId:
        type: integer
      description:
        type: string
      difficulty:
        type: integer
      duration:
        type: integer
      statusId:
        type: integer
      title:
        type: string
    type: object
  domain.TaskDeleteReq:
    properties:
      id:
        type: integer
      updateUserId:
        type: integer
    type: object
  domain.TaskGetDataList:
    properties:
      createdAt:
        type: string
      description:
        type: string
      difficulty:
        type: integer
      duration:
        type: integer
      id:
        type: integer
      status:
        type: string
      statusId:
        type: integer
      title:
        type: string
    type: object
  domain.TaskStatusGetDataList:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  domain.TaskUpdateReq:
    properties:
      description:
        type: string
      difficulty:
        type: integer
      duration:
        type: integer
      id:
        type: integer
      statusId:
        type: integer
      title:
        type: string
      updateUserId:
        type: integer
    type: object
  domain.UserAddReq:
    properties:
      createUserId:
        type: integer
      developerLevel:
        type: integer
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  domain.UserDeleteReq:
    properties:
      id:
        type: integer
      updateUserId:
        type: integer
    type: object
  domain.UserGetDataList:
    properties:
      createdAt:
        type: string
      developerWorkHourDifficulty:
        type: integer
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
    type: object
  domain.UserUpdateReq:
    properties:
      developerLevel:
        type: integer
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      updateUserId:
        type: integer
    type: object
info:
  contact: {}
paths:
  /distributeTasks:
    get:
      consumes:
      - application/json
      description: Distribute tasks to users
      parameters:
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Distribute tasks
      tags:
      - Distribute Tasks
  /login:
    post:
      consumes:
      - application/json
      description: Login to the application
      operationId: login
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login
      tags:
      - Auth
  /tasks/add:
    post:
      consumes:
      - application/json
      description: Adds a new task to the task list
      operationId: add-task
      parameters:
      - description: Task Add to Database
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/domain.TaskAddReq'
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a new task
      tags:
      - Tasks
  /tasks/delete:
    delete:
      consumes:
      - application/json
      description: Delete a task
      operationId: delete-task
      parameters:
      - description: Task object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/domain.TaskDeleteReq'
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a task
      tags:
      - Tasks
  /tasks/getAll:
    get:
      consumes:
      - application/json
      description: Get all tasks
      operationId: get-all-tasks
      parameters:
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.TaskGetDataList'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all tasks
      tags:
      - Tasks
  /tasks/getById/{id}:
    get:
      consumes:
      - application/json
      description: Get a task by ID
      operationId: get-task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TaskGetDataList'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a task by ID
      tags:
      - Tasks
  /tasks/taskStatus:
    get:
      consumes:
      - application/json
      description: Get all task status
      operationId: get-all-tasks-status
      parameters:
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.TaskStatusGetDataList'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all task status
      tags:
      - Tasks
  /tasks/update:
    put:
      consumes:
      - application/json
      description: Update a task
      operationId: update-task
      parameters:
      - description: Task object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/domain.TaskUpdateReq'
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: task Update
      tags:
      - Tasks
  /users/add:
    post:
      consumes:
      - application/json
      description: Adds a new user to the user list
      operationId: add-user
      parameters:
      - description: User Add to Database
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserAddReq'
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a new user
      tags:
      - Users
  /users/delete:
    delete:
      consumes:
      - application/json
      description: Delete a user
      operationId: delete-user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserDeleteReq'
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a user
      tags:
      - Users
  /users/getAll:
    get:
      consumes:
      - application/json
      description: Get all users
      operationId: get-all-users
      parameters:
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserGetDataList'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all users
      tags:
      - Users
  /users/getById/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      operationId: get-user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserGetDataList'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user by ID
      tags:
      - Users
  /users/update:
    put:
      consumes:
      - application/json
      description: Update a user
      operationId: update-user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserUpdateReq'
      - description: ' you must start Bearer and then space and then token'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a user
      tags:
      - Users
swagger: "2.0"
